use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

target 'AutoModel_Example' do
  pod 'AutoModel', :path => '../'

  target 'AutoModel_Tests' do
    inherit! :search_paths

    
  end
end
